version: "3.9"
services:
  mysql:
    image: mysql/mysql-server:8.0
    environment:
      - MYSQL_DATABASE=todo
      - MYSQL_USER=manabie
      - MYSQL_PASSWORD=Manabie@2022
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"